export const notesPageStyles = {
  wrapper: 'flex-1 flex flex-col bg-white overflow-hidden px-8 py-8 gap-8 overflow-y-auto',
  header: 'flex items-center justify-between mb-8 shrink-0',
  title: 'text-3xl font-bold font-headline-md text-primary',
  searchBox: 'flex items-center gap-2 w-72 bg-surface border border-outline-variant/40 rounded-xl py-2 px-4 focus-within:border-primary-container transition-colors',
  searchIcon: 'w-5 h-5 text-outline',
  searchInput: 'w-full bg-transparent border-0 outline-none text-sm text-on-surface placeholder:text-outline/70',
  contentArea: 'flex-1 overflow-y-auto p-8',
  loadingText: 'min-h-[50vh] flex items-center justify-center text-sm text-outline',
  errorRow: 'flex items-center justify-center gap-2 py-12 text-center text-error text-sm',
  errorIcon: 'w-5 h-5',
  emptyWrap: 'max-w-md mx-auto py-20 flex flex-col items-center gap-4 text-center',
  emptyIconBadge: 'w-12 h-12 rounded-xl bg-surface-container-low border border-outline-variant/50 flex items-center justify-center text-outline-variant mx-auto mb-4',
  emptyIcon: 'w-5 h-5',
  emptyHeading: 'text-lg font-semibold text-on-surface',
  emptyBodyText: 'text-sm leading-relaxed text-outline',
  createButton: 'inline-flex items-center justify-center px-6 py-2.5 bg-primary-container text-white text-sm font-semibold rounded-xl shadow-sm hover:bg-primary transition-all active:scale-95 cursor-pointer',
  createIcon: 'w-5 h-5',
  grid: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6',
} as const

export const noteCardStyles = {
  card: 'relative flex flex-col justify-between gap-4 p-5 bg-surface border border-outline-variant/30 rounded-2xl cursor-pointer hover:border-primary-container hover:shadow-sm hover:-translate-y-px transition-all group',
  titleRow: 'flex justify-between items-start',
  title: 'pr-6 text-base font-semibold text-on-surface leading-snug group-hover:text-primary',
  menuButtonWrap: 'absolute top-4 right-4 z-10',
  menuButton: 'p-1 rounded-lg text-outline hover:bg-surface-container hover:text-primary transition-colors',
  menuIcon: 'w-5 h-5',
  dropdown: 'absolute right-0 top-full mt-1 w-36 bg-white border border-outline-variant/40 rounded-xl shadow-lg py-1 z-20',
  dropdownItem: 'w-full flex items-center gap-2 py-2 px-4 text-left text-xs transition-colors hover:bg-surface hover:text-primary',
  dropdownItemDanger: 'w-full flex items-center gap-2 py-2 px-4 text-left text-xs transition-colors hover:bg-surface hover:text-primary text-error hover:bg-error-container/30',
  dropdownIcon: 'w-5 h-5',
  preview: 'mt-2 text-xs leading-relaxed text-outline line-clamp-3',
  footer: 'flex items-center justify-between pt-4 border-t border-outline-variant/20 text-[11px] font-medium text-outline',
} as const
